version: '2'
services:

    strawberry:
        build: .
        image: andrievsky/strawberry:latest
        container_name: strawberry
        hostname: strawberry
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./var:/data
        ports:
            - "80:8080"

        environment:
           - ENGINE=MEMORY
           - BOLT_FILE=/data/strawberry.bd
