### get resource by id
GET {{host}}/api/v1/resource/{{id}}

### create resource
POST {{host}}/api/v1/resource
Content-Type: application/json

{
    "type": "Raccoon",
	"description": "Resource Description",
	"location":  { "lon": 1.1, "lat": 2.2 }
}

### list of all resources
GET {{host}}/api/v1/list

###